<?php

/**
 * Implements hook_form_FORM_ID_alter
 */
function hc_register_form_user_register_form_alter(&$form, &$form_state) {

  // change default page title
  drupal_set_title(t('Registreer jezelf om deel te nemen'));
  
  // user picture fieldset
  $form['picture']['#title'] = '';
  $form['picture']['#title_display'] = FALSE;
  $form['picture']['#weight'] = '8';
  $form['picture']['picture_upload']['#description'] = '';
  
  

	// persoonlijke gegevens
	$form['persoonlijke_data'] = array(
	  '#type' => 'markup',
		'#markup' => '<h2 class="legend">' . t('Persoonlijke data') . '</h2>',
	  '#weight' => '-100',
	);
	
	
	// login gegevens
	$form['login_gegevens'] = array(
	  '#type' => 'markup',
	  '#prefix' => '<div class="separator">&nbsp;</div>',
	  '#markup' => '<h2 class="legend">' . t('Login gegevens') . '</h2>',
	  '#weight' => '9',
	);
	
	$form['extra'] = array(
	  '#type' => 'markup',
	  '#markup' => '<div class="separator">&nbsp;</div>',
	  '#weight' => '80',
	);
	
	// user account 
	$form['account']['mail']['#description'] = '';
	$form['account']['pass']['#description'] = '';

	// nieuws
	$form['field_nieuws']['#weight'] = 90;

	// reglement
	$form['field_reglement']['#weight'] = 100;
	
	foreach ($form['field_reglement'] as $delta => $value) {
	  if (is_array($value)) {
	    if (isset($value['#options']['akkoord'])) {
	      $form['field_reglement'][$delta]['#options']['akkoord'] = "Ik ga akkoord met het <a href='#'>wedstrijdreglement.</a>";
	    }
	  }
	}
	
	// motivatie textarea: TODO: language SUPPORT?
	$form['field_user_motivatie']['und'][0]['value']['#resizable'] = FALSE;
	
	// submit button
	$form['actions']['submit']['#value'] = t('Registreer');

/*
	print_r($form);
	exit();
*/

}


/**
 * Implements hook_form_alter
 */
function hc_register_form_user_profile_form_alter(&$form, &$form_state, $form_id) {
  $form['locale']['#weight'] = 23;

	// motivatie textarea: TODO: language SUPPORT?
	$form['field_user_motivatie']['und'][0]['value']['#resizable'] = FALSE;

  // FB message bovenaan zetten
	if (isset($form['account']['fboauth'])) {
	  $form['facebook'] = array(
	    '#type' => 'markup',
	    '#markup' => $form['account']['fboauth']['#markup'],
	    '#weight' => -999,
	  );
	  unset($form['account']['fboauth']);
	}

	foreach ($form['field_reglement'] as $delta => $value) {
	  if (is_array($value)) {
	    if (isset($value['#options']['akkoord'])) {
	      $form['field_reglement'][$delta]['#options']['akkoord'] = "Ik ga akkoord met het <a href='#'>wedstrijdreglement.</a>";
	    }
	  }
	}


}



/**
 * Implements hook_preprocess_page
 */
function hc_register_preprocess_page(&$vars, $hook) {
  if (arg(0) == 'user') {
		$vars['tabs'] = array();
  }
}