<?php

/**
 * Implements hook_init
 */
function hc_partners_init() {
  $path = drupal_get_path('module', 'hc_partners');
  drupal_add_js($path . '/hc_partners.js');
}

/**
 * Implements hook_menu
 */
function hc_partners_menu() {
  $items = array();
  
  $items['get-partner/%/%'] = array(
    'page callback' => 'hc_partners_render',
    'page arguments' => array(1, 2),
    'access arguments' => array('access content'),
  );
  
  return $items;
}


/**
 * Implements hook_preprocess_page
 */
function hc_partners_preprocess_page(&$vars) {

	// make specific partner visible
	if (isset($_GET['partner_nid'])) {
	
		$partner_nid = $_GET['partner_nid'];
		$partner = node_load($partner_nid);
		$partner_type = $partner->type;
	
	  $path = drupal_get_path('module', 'hc_partners');
	  
	  $settings['hc_partner'] = array(
	    'partner_nid' => $partner_nid,
	    'partner_type' => $partner_type,
	  );
	  
	  drupal_add_js($settings, 'setting');
		drupal_add_js($path . '/hc_partners_direct_link.js');
  }


}



function hc_partners_render($nid, $type) {
 
 	switch ($type) {
 	  case 'companies':
		  $output = views_embed_view('partners', 'block_3', $nid); 	  
		  break;
		case 'sponsors':
		  $output = views_embed_view('partners', 'block_5', $nid); 	  
		  break;
 	}
 
  print $output;
  exit();
}